/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["run_task"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            message: string;
        };
        ListTasksRequest: {
            /** @example /Users/johndoe/documents/github/example-project */
            cwd: string;
        };
        ListTasksResponse: {
            Success: components["schemas"]["ListTasksResponseBody"];
        } | {
            Error: components["schemas"]["ErrorResponse"];
        };
        ListTasksResponseBody: {
            /** @description The list of tasks that are defined in the task.config.json file */
            tasks: {
                [key: string]: components["schemas"]["Task"];
            };
        };
        StartTaskRequest: {
            cwd: string;
            task: string;
        };
        StartTaskResponse: {
            Success: components["schemas"]["StartTaskResponseBody"];
        } | {
            Error: components["schemas"]["ErrorResponse"];
        };
        StartTaskResponseBody: {
            runId: string;
        };
        Task: {
            /** @description The command that the task will run. */
            command?: string | null;
            /** @description Any other task names that this task depends on. */
            dependsOn?: string[] | null;
            dependsOnTasks?: {
                [key: string]: components["schemas"]["Task"];
            } | null;
            /** @description Whether the task is optional. If true, the task will only run if started manually. */
            optional?: boolean | null;
            /** @description Subtasks of this task. Keys must be unique task names. */
            tasks?: {
                [key: string]: components["schemas"]["Task"];
            } | null;
            /** @description The title of the task. */
            title?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_tasks: {
        parameters: {
            query: {
                /** @description The current working directory to load the task config from */
                cwd: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTasksResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    run_task: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartTaskRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartTaskResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
